image: golang:1.11-stretch

stages:
  - test

lint:
  stage: test
  before_script:
    - go get golang.org/x/lint/golint
    - go mod download
  script:
    - go build
    - golint -set_exit_status ./...

