/*
Robinhood API

Robinhood API Documentation

API version: 3.0.1

*/

// Code generated by ryang Generator (https://openapi-generator.tech); DO EDIT. =)

package openapi

/* manually added

 */

type EquityComponent struct {
	ID         *string `json:"id,omitempty"`
	Instrument *string `json:"instrument,omitempty"`
	Price      *string `json:"price,omitempty"`
	Quantity   *string `json:"quantity,omitempty"`
	Side       *string `json:"side,omitempty"`
	Symbol     *string `json:"symbol,omitempty"`
}

type OptionAssignment struct {
	Account          *string           `json:"account,omitempty"`
	CashComponent    *string           `json:"cash_component,omitempty"`
	ChainID          *string           `json:"chain_id,omitempty"`
	CreatedAt        *string           `json:"created_at,omitempty"`
	Direction        *string           `json:"direction,omitempty"`
	EquityComponents []EquityComponent `json:"equity_components,omitempty"`
	EventDate        *string           `json:"event_date,omitempty"`
	ID               *string           `json:"id,omitempty"`
	Option           *string           `json:"option,omitempty"`
	Position         *string           `json:"position,omitempty"`
	Quantity         *string           `json:"quantity,omitempty"`
	SourceRefID      *string           `json:"source_ref_id,omitempty"`
	State            *string           `json:"state,omitempty"`
	TotalCashAmount  *string           `json:"total_cash_amount,omitempty"`
	Type             *string           `json:"type,omitempty"`
	UnderlyingPrice  *string           `json:"underlying_price,omitempty"`
	UpdatedAt        *string           `json:"updated_at,omitempty"`
}

type GetEventsResponse struct {
	Next     *string             `json:"next,omitempty"`
	Previous *string             `json:"previous,omitempty"`
	Results  *[]OptionAssignment `json:"results,omitempty"`
}

/* manually added

 */
