/*
Robinhood API

Robinhood API Documentation

API version: 3.0.1

*/

// Code generated by ryang Generator (https://openapi-generator.tech); DO EDIT. =)

package openapi

/* manually added

 */

type GetStockSplitResponse struct {
	Next     *string        `json:"next,omitempty"`
	Previous *string        `json:"previous,omitempty"`
	Results  *[]interface{} `json:"results,omitempty"`
}

/* manually added

 */
